version: '3.1'

services:
  php:
    build: ./src
    environment:
      - MYSQL_USER=guestbook
      - MYSQL_PASS=admin123
      - MYSQL_DATABASE=guestbook
    ports:
      - 8001:80
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
      
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "6033:3306"

volumes:
  mysqldata: null
