version: '3.1'

services:
  php:
    build: ./src
    ports:
      - 8001:80

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
